### PR TITLE
Display payment points in the leaderboard.

### PR DESCRIPTION
**Pull request by soffokl**
The following environment variable required to resolve prometheus basic auth:
`PROMETHEUS_HEAD: '{"Authorization": "Basic QWxhZGRpbjpPcGVuU2VzYW1l"}'`
`PROMETHEUS_URL: "https://victoriametrics.mysterium.network"`
This is just an example of the Authorization header, not real values. 🌚

image

### CODE REVIEW

**Comment by tadaskay** [comment]
Are those credentials actual or just an example? (must either change or mention that those are just an example)

**Comment by soffokl** [comment]
This is just an example, updated description.

**Comment by chompomonim** [comment]
Why points are not divided by 8? MYSTT has 8 symbols after comma.

**Comment by soffokl** [comment]
Because this is just a "points", not an MYSTT. It could be changed later to be MYSTT-earned+availabilty+traffic+whatever, but this will keep being abstract points.

**Pull request merged**
